### ISSUE TITLE
Threads don't terminate

### ISSUE THREAD

**Issue by inserpio** [neo4j/neo4j-java-driver#330]
While trying to solve [this issue](https://github.com/neo4j-contrib/neo4j-jdbc/issues/94) on the neo4j-jdbc-driver, I noticed that if I turn TLS encryption off this test doesn't terminate:

```
@Test
public void issue94OnlyJavaBoltDriver() {
  for (int i = 0; i < 2000; i++) {		
    Config.ConfigBuilder builder = build();
    builder = builder.withEncryptionLevel(Config.EncryptionLevel.NONE);
    Config config = builder.toConfig();
    Driver driver = GraphDatabase.driver( "bolt://localhost", AuthTokens.basic( "neo4j", "larus" ), config );
    try (Session s = driver.session()) {
      System.out.println(i);
    }
    catch (Exception e) {
      Assert.fail(e.getMessage());
    }
    driver.close();
  }
  System.out.println("done.");
}	
```

but as soon as I comment `builder.withEncryptionLevel(Config.EncryptionLevel.NONE);` then the test terminates successfully.

Yes, I shouldn't create a new driver instance per iteration, but on the other side I'm also closing it, so I'd expect the cycle not to result in any resource leak.

The problem is that threads remain opened.

Thanks for your kind reply.

**Comment by zhenlineo** [comment]
Hi, which driver version you are using saw this problem?

I tried with the 1.1 branch and it passed successfully on my machine...

**Comment by inserpio** [comment]
Hi @zhenlineo, I just committed a sample project to illustrate this my issue. 
https://github.com/inserpio/neo4j-java-bolt-driver-thread-issue
I don't know why it's working for you. I guess it's machine dependent: the more capacity the machine has and the better probability to terminate it has?
With 1.2.0 the problem disappear!
Finally, I'm running this test with neo4j 3.1.0 on my macbook pro 10.11.6.

**Comment by lutovich** [comment]
Hi @inserpio,

We were able to reproduce the described problem. Could you please check `debug.log` of the Neo4j instance after the test hangs?

On my machine it has an OOM error like this:
`java.lang.OutOfMemoryError: unable to create new native thread`

This happens because each new session is obtained from a new driver and so there is no connection pool to take connections from. So each iteration of the test creates a new network connection and forces database to spawn a new thread to handle that connection. Problem does not happen in 1.2 because there session is decoupled from connection so `driver.session()` call does not create connection, they are instead created/obtained form the pool lazily when needed to execute queries/transactions.

**Comment by inserpio** [comment]
Great. Thanks @lutovich.
I can confirm both the OOM error and that it works with 1.2.
I'd not use the driver like that (new session from new driver), but the issue we got on the JDBC driver translates like this on the java bolt driver :-( and I wanted to notify that to you.

Coming back to my sample project above, given that I'm closing the driver connection at the very end of every iteration + session is auto-closable, I thought about a resource leak from your side.
If it's too hard to correct that in previous (to 1.2) releases, then don't worry: we're planning to upgrade the JDBC driver to this your last 1.2 version.

Cheers, Lorenzo.

**Comment by lutovich** [comment]
@inserpio when session it closed it's connection is returned to the pool. Then when driver is closed all used connections are closed. So in the test database is basically forced to create & destroy threads in a tight loop and hits memory/OS limitation. I guess problem can still happen in 1.2 when created session is used to execute query or start a transaction.

Backporting session-connection decoupling to 1.1 would be quite a big and risky change. It is probably reasonable to not do it especially that version with a fix is available.

Thanks!
